site_name: Руководство по работе с ботом
site_url: https://proraschety.github.io/fireengin-bot-guide/
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Переключить на светлый режим
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Переключить на темный режим
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    # - icon: simple/youtube
    #   link: https://youtube.com/@james-willett
    #   name: Смотреть на YouTube

    # - icon: simple/github
    #   link: https://github.com/ProRaschety/fireengin-bot-docs

    - icon: simple/telegram
      link: https://t.me/pro_raschety
      name: Telegram-канал "Про расчеты"

    # - icon: material/play-circle
    #   link: https://rutube.ru/channel/30851782/
    #   name: Смотреть на RuTube


copyright: Copyright &copy; 2023-2025 Ravshan I.